### PR TITLE
Helm chart for CodeGen on Xeon

### PR DESCRIPTION
**Pull request by yongfengdu**
Two services in total, the codegen service is depending on tgi. Current tgi supports CPU only, will add Gaudi support later. You'll need a HuggingFace token in values.yaml
hf_token: "yourowntokenfromhuggingface"
Use "helm install codegen codegen" to deploy.

## Type of Change

feature

## Description

Add CodeGen helm charts for Xeon

## How has this PR been tested?
1. Modify the values.yaml hf_token with your huggingface API token
2.  helm install codegen codegen
3. curl http://test-codegen/v1/code_generation -X POST -H "Content-Type: application/json" -d '{"prompt": "def print_hello_world():", "max_new_tokens": 128, "stream": true}'

### CODE REVIEW

**Review by daisy-ycguo — COMMENTED** [review]
Thank you for your PR. I tested as your describe, but I got error. I think `/home/ubuntu/models` should be configurable via value.yaml.

```
$ kubectl get pods
NAME                                                        READY   STATUS              RESTARTS     AGE
codegen-789f4f44bb-d2xj5                                    1/1     Running             0            2m13s
codegen-tgi-5b6cb66c4f-hwnhg                                0/1     ContainerCreating   0            2m13s

$ kubectl describe pod codegen-tgi-5b6cb66c4f-hwnhg
Name:             codegen-tgi-5b6cb66c4f-hwnhg
Namespace:        default
Priority:         0
Service Account:  default
Node:             b4969184c7f8.jf.intel.com/10.165.58.24
Start Time:       Wed, 15 May 2024 02:29:13 -0700
Labels:           app.kubernetes.io/instance=codegen
                  app.kubernetes.io/name=tgi
                  pod-template-hash=5b6cb66c4f
Annotations:      <none>
Status:           Pending
IP:
IPs:              <none>
Controlled By:    ReplicaSet/codegen-tgi-5b6cb66c4f
Containers:
  tgi:
    Container ID:
    Image:          ghcr.io/huggingface/text-generation-inference:1.4
    Image ID:
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:
      MODEL_ID:  m-a-p/OpenCodeInterpreter-DS-6.7B
      PORT:      80
    Mounts:
      /data from model-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-hqb45 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  model-volume:
    Type:          HostPath (bare host directory volume)
    Path:          /home/ubuntu/models
    HostPathType:  Directory
  kube-api-access-hqb45:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age                  From               Message
  ----     ------       ----                 ----               -------
  Normal   Scheduled    2m19s                default-scheduler  Successfully assigned default/codegen-tgi-5b6cb66c4f-hwnhg to b4969184c7f8.jf.intel.com
  Warning  FailedMount  12s (x9 over 2m19s)  kubelet            MountVolume.SetUp failed for volume "model-volume" : hostPath type check failed: /home/ubuntu/models is not a directory
```

**Review by daisy-ycguo — CHANGES_REQUESTED** [review]
I think you need a README.md to describe how to use this chart.

**Comment by yongfengdu** [comment]
> Thank you for your PR. I tested as your describe, but I got error. I think `/home/ubuntu/models` should be configurable via value.yaml.
> 
> ```
> $ kubectl get pods
> NAME                                                        READY   STATUS              RESTARTS     AGE
> codegen-789f4f44bb-d2xj5                                    1/1     Running             0            2m13s
> codegen-tgi-5b6cb66c4f-hwnhg                                0/1     ContainerCreating   0            2m13s
> 
> $ kubectl describe pod codegen-tgi-5b6cb66c4f-hwnhg
> Name:             codegen-tgi-5b6cb66c4f-hwnhg
> Namespace:        default
> Priority:         0
> Service Account:  default
> Node:             b4969184c7f8.jf.intel.com/10.165.58.24
> Start Time:       Wed, 15 May 2024 02:29:13 -0700
> Labels:           app.kubernetes.io/instance=codegen
>                   app.kubernetes.io/name=tgi
>                   pod-template-hash=5b6cb66c4f
> Annotations:      <none>
> Status:           Pending
> IP:
> IPs:              <none>
> Controlled By:    ReplicaSet/codegen-tgi-5b6cb66c4f
> Containers:
>   tgi:
>     Container ID:
>     Image:          ghcr.io/huggingface/text-generation-inference:1.4
>     Image ID:
>     Port:           80/TCP
>     Host Port:      0/TCP
>     State:          Waiting
>       Reason:       ContainerCreating
>     Ready:          False
>     Restart Count:  0
>     Environment:
>       MODEL_ID:  m-a-p/OpenCodeInterpreter-DS-6.7B
>       PORT:      80
>     Mounts:
>       /data from model-volume (rw)
>       /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-hqb45 (ro)
> Conditions:
>   Type              Status
>   Initialized       True
>   Ready             False
>   ContainersReady   False
>   PodScheduled      True
> Volumes:
>   model-volume:
>     Type:          HostPath (bare host directory volume)
>     Path:          /home/ubuntu/models
>     HostPathType:  Directory
>   kube-api-access-hqb45:
>     Type:                    Projected (a volume that contains injected data from multiple sources)
>     TokenExpirationSeconds:  3607
>     ConfigMapName:           kube-root-ca.crt
>     ConfigMapOptional:       <nil>
>     DownwardAPI:             true
> QoS Class:                   BestEffort
> Node-Selectors:              <none>
> Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
>                              node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
> Events:
>   Type     Reason       Age                  From               Message
>   ----     ------       ----                 ----               -------
>   Normal   Scheduled    2m19s                default-scheduler  Successfully assigned default/codegen-tgi-5b6cb66c4f-hwnhg to b4969184c7f8.jf.intel.com
>   Warning  FailedMount  12s (x9 over 2m19s)  kubelet            MountVolume.SetUp failed for volume "model-volume" : hostPath type check failed: /home/ubuntu/models is not a directory
> ```

Thanks for the test, the failure is due to an non-exists directory on the testing host. The directory is supposed to put predownloaded/cached models.
I will add a readme file to put the config values there.

**Comment by leslieluyu** [comment]
I've already tested the helm chart, apart from the questions raised by Daisy, all things run smoothly. There is one suggestion,  I think we should mention in the README that it may take several minutes for the tgi to download and warm up the model. Before sending the request via cURL, the user should first verify that the TGI service is ready.

**Comment by jfding** [comment]
Another suggestion is, maybe we can put tgi* services' charts to a separate place, like <REPO>/helm-charts/GenAIComps/foo-bar

**Comment by yongfengdu** [comment]
We'll do this after we have the official helm chart repo. If without repo, the helm dependency check will fail because there is no place to download.
> Another suggestion is, maybe we can put tgi* services' charts to a separate place, like /helm-charts/GenAIComps/foo-bar

**Comment by yongfengdu** [comment]
Added startupProbe and readinessProbe to handle this slow start issue. In the README.md, also mentioned that if there is no local cache, it will need time to download models.
> I've already tested the helm chart, apart from the questions raised by Daisy, all things run smoothly. There is one suggestion, I think we should mention in the README that it may take several minutes for the tgi to download and warm up the model. Before sending the request via cURL, the user should first verify that the TGI service is ready.

**Review by leslieluyu — APPROVED** [review]
The Helm chart of CodeGen installation has been tested, and the service availability has been verified.

**Pull request merged**
