### PR TITLE
relocate files according to new dir structure

### PR DESCRIPTION
**Pull request by jfding**
## Description

relocate files according to new dir structure:
manifests/common/ui.yaml ->  microservices-connector/config/manifests/ui.yaml

## Issues

n/a

## Type of change

code structure management

## Dependencies

n/a

## Tests

CI jobs

### CODE REVIEW

**Comment by lianhao** [comment]
@jfding  PR #273 has already covered this

**Comment by zhlsunshine** [comment]
> @jfding PR #273 has already covered this

Hi @lianhao, what do you mean covered by PR #273? It seems that there is no business with these 2 PRs

**Comment by lianhao** [comment]
I've already moved the newly land-in ui.yaml and rename it to chatqna-ui

**Comment by lianhao** [comment]
> > @jfding PR #273 has already covered this
> 
> Hi @lianhao, what do you mean covered by PR #273? It seems that there is no business with these 2 PRs

Sorry, I mean PR #267

**Comment by jfding** [comment]
Just noticed #275 has covered this issue and merged, let me close this PR.

**Pull request closed without merging**
