### PR TITLE
GMC: Support new component

### PR DESCRIPTION
**Pull request by KfreeZ**
## Description

Add 4 new components of AudioQnA : whisper, asr, tts, speecht5

Improve log information

## Issues

 `n/a`

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)

## Dependencies

 `n/a`

### CODE REVIEW

**Comment by zhlsunshine** [comment]
Need to wait for the validation of such example.

**Comment by KfreeZ** [comment]
> Need to wait for the validation of such example.

as we have discussed, please open an issue to track the service problem and I removed examples to avoid confusion.

**Review by zhlsunshine — APPROVED** [review]
LGTM

**Comment by zhlsunshine** [comment]
@irisdingbj @KfreeZ Let's go on the track of [issue#340](https://github.com/opea-project/GenAIComps/issues/340)

**Pull request merged**
