### PR TITLE
tgi: revert xeon version to 2.2.0

### PR DESCRIPTION
**Pull request by lianhao**
## Description

Due to bug opea-project/GenAIExamples#636, revert tgi xeon version to 2.2.0.

## Issues

opea-project/GenAIExamples#636

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Dependencies

n/a.

## Tests

Describe the tests that you ran to verify your changes.

### CODE REVIEW

**Review by daisy-ycguo — APPROVED** [review]
lgtm

**Review by yongfengdu — APPROVED** [review]

**Comment by lianhao** [comment]
The reason why gmc xeon test fails is because the model used by gmc chatqna CI test `bigscience/bloom-560m` doesn't work with tgi 2.2.0 anymore. We use `bigscience/bloom-560m` in GMC xeon CI because of bug #258.

**Comment by KfreeZ** [comment]
note: TGI 2.2.0 cannot work with bigscience/bloom-560m

**Review by KfreeZ — APPROVED** [review]
thanks for fixing this!!!

**Comment by eero-t** [comment]
> The reason why gmc xeon test fails is because the model used by gmc chatqna CI test `bigscience/bloom-560m` doesn't work with tgi 2.2.0 anymore. We use `bigscience/bloom-560m` in GMC xeon CI because of bug #258.

Whereas 2.0.x & 2.1.x versions regressed TGI Prometheus support so one does not get any token metrics out of them (although they worked fine with TGI 1.x).  That was fixed only in 2.2.0: https://github.com/huggingface/text-generation-inference/issues/2184

**Pull request merged**
