### PR TITLE
Add Grafana dashboard for monitoring OPEA application scaling in k8s

### PR DESCRIPTION
**Pull request by eero-t**
## Description

Adds Grafana dashboard for monitoring OPEA application scaling:
* How many of the application and its TGI + TEI pods are created, ready and in use
* How many requests they are processing (min and max across all replicats)
* How many failures they are reporting (sum across replicas)

And a helper script for installing dashboard k8s `configMap`s for Grafana.

Unlike earlier ChatQnA dashboard, this handles multiple OPEA application having same names but being in separate namespaces.  User selects namespace and then the OPEA application from that.  If cluster has only one running, Dashboard will default to that.

(Therefore it does not make sense to install dashboard with application specific Helm charts, as it can cover all apps that use TGI for LLM, i.e. most of them.)

## Issues

`n/a`.

## Type of change

- [x] New feature (non-breaking change which adds new functionality)

## Dependencies

`n/a`.

## Tests

Manual testing of the script and dashboard working.

### CODE REVIEW

**Comment by eero-t** [comment]
Currently dashboard relies on HTTP `inprogress` metric for how many pending requests application has: https://github.com/opea-project/GenAIComps/pull/845

But depending on whether following PR is merged for v1.1, that particular metric may need to be changed before v1.1: https://github.com/opea-project/GenAIComps/pull/864

**Comment by eero-t** [comment]
I can add blurb about this also to README, but scaling is currently a bit of corner case, so IMHO it could come also in next release.

Larger question about Observability README, and things it refers to, is what to do with `chatqna/` sub-directory content here, now that Helm charts have more generic monitoring support for OPEA applications.

The dashboards under that:
* `queue_size_embedding_rerank_tgi.json`: some queries in that do not have any selectors, some use `service` selector
* `tgi_grafana.json`: queries use `container` selector (`container="$service"`)

I.e. neither handles properly case when cluster is running multiple TGI instances, or separate TEI instances for different OPEA application instances.

**Review by jfding — APPROVED** [review]

**Review by jfding — APPROVED** [review]

**Comment by eero-t** [comment]
FYI: I'm going to change "Failures" heading to "Incomplete requests".   I do not think half of TGI requests are failures, but e.g. frontend requests being split to 2 backend ones, so only half of them are "complete".

**Comment by eero-t** [comment]
Dashboard changes:
* Changed HTTP metric to one that will come with: https://github.com/opea-project/GenAIComps/pull/864
* Lowered scaling & failures rows so that dashboard first better to screen
*  "Failures" -> "Incomplete requests" header change

**Review by lianhao — APPROVED** [review]

**Review by poussa — APPROVED** [review]

**Pull request merged**
