### PR TITLE
Add vLLM+HPA support to ChatQnA Helm chart

### LINKED ISSUE #631: [ci-auto] remove "--enforce-eager" for better vLLM perf
## GenAIExample ChatQnA compose.yaml got changed

Below files are changed in [this commit](https://github.com/opea-project/GenAIExamples/commit/4c01e1464273ae49909ab1eca337176588f8a027)

- ChatQnA/docker_compose/intel/hpu/gaudi/compose_vllm.yaml

Please verify if the helm charts and manifests need to be changed accordingly.

> This issue was created automatically by CI.

### PR DESCRIPTION
**Pull request by eero-t**
## Description

Add vLLM + HPA support for _ChatQnA_ Helm charts.

Similarly to how it's already done in _Agent_ component, there's `tgi.enabled` and `vllm.enabled` flags for selecting which LLM will be used.

Note: _ChatQnA_ does not yet support using vLLM for embedding & reranking [1], so HF TEI is still used for those.

[1] https://github.com/opea-project/GenAIExamples/pull/1237

## Issues

Fixes https://github.com/opea-project/GenAIInfra/issues/608 partially.
Fixes #631.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)

## New dependencies

`n/a`

## Tests

Manual testing on top of `main` HEAD / v1.1 images.

### CODE REVIEW

**Comment by eero-t** [comment]
CI issues:
* LLM-uservice: `openai.NotFoundError: Error code: 404 - {'object': 'error', 'message': 'The model `meta-llama/Meta-Llama-3-8B-Instruct` does not exist.', 'type': 'NotFoundError', 'param': None, 'code': 404}`
  * Bug already in the CI/repo, pre-existing Helm chart refers to model not present in CI => I can fix it
* DocSum: `100.83.111.229:5000/opea/llm-docsum-vllm:latest: not found`
  * Bug in OPEA image creation, that image is missing from DockerHub & CI => somebody else needs to fix that

**Comment by eero-t** [comment]
This overlaps partly with https://github.com/opea-project/GenAIInfra/pull/403.

**Comment by eero-t** [comment]
Added HPA support for ChatQnA / vLLM.

**Comment by eero-t** [comment]
This bug for `llm-uservice, gaudi, ci-vllm-gaudi-values, common` is weird:
```
openai.NotFoundError: Error code: 404 - {'object': 'error', 'message': 'The model `meta-llama/Meta-Llama-3-8B-Instruct` does not exist.', 'type': 'NotFoundError', 'param': None, 'code': 404}
```

Because neither that CI file, nor `values.yaml` specifies that model for `llm-uservice`:
```
$ git  grep -l '^[^#]*Meta-Llama-3-8B-Instruct'
helm-charts/common/llm-uservice/ci-faqgen-values.yaml
helm-charts/common/llm-uservice/variant_faqgen-values.yaml
helm-charts/faqgen/README.md
helm-charts/faqgen/values.yaml
```

So CI either invents that model from thin air, or is using wrong CI file (`faqgen` instead of `vllm-gaudi` one)!

**Comment by eero-t** [comment]
Changes:
* Cherry-picked changes from https://github.com/opea-project/GenAIInfra/pull/632
* Dropped vLLM support for _DocSum_ as required image is missing
* Rebased to latest `main`

**Comment by eero-t** [comment]
Dropped fix for model ID, it's specific to DocSum & FaqGen specific `llm-uservice` variants.  Text generation `llm-uservice`  variant uses different env var name from those (which IMHO is bug, but for code in another repo).

I'll add workaround for it in separate PR for DocSum vLLM suport.

**Review by lianhao — APPROVED** [review]

**Review by yongfengdu — APPROVED** [review]

**Pull request merged**
