### PR TITLE
Enhance the switch mode for GMC router service required

### PR DESCRIPTION
**Pull request by zhlsunshine**
## Description

This PR is submitted for https://github.com/opea-project/GenAIInfra/issues/143, there are some limitations of the current switch mode in GMC, such as only one switch condition can be supported in GMC router.
This PR make sure that all conditions can be handled in switch mode.

## Issues

https://github.com/opea-project/GenAIInfra/issues/143

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)

## Dependencies

 `n/a`.

## Tests

**Switch mode with parameter model_id==intel**
image
image

**Switch mode with parameter model_id==llama**
image
image

### CODE REVIEW

**Review by mkbhanda — APPROVED** [review]
LTGM

**Comment by daisy-ycguo** [comment]
@zhlsunshine I just wonder if you have any unit tests or e2e tests to cover this case?

**Comment by zhlsunshine** [comment]
> @zhlsunshine I just wonder if you have any unit tests or e2e tests to cover this case?

Hi @daisy-ycguo, this enhancement is related to route service which has been tested by before unit test.

**Review by daisy-ycguo — APPROVED** [review]
lgtm

**Review by mkbhanda — COMMENTED** [review]
LGTM

**Pull request merged**
