### PR TITLE
Adapt to latest vllm changes

### LINKED ISSUE #631: [ci-auto] remove "--enforce-eager" for better vLLM perf
## GenAIExample ChatQnA compose.yaml got changed

Below files are changed in [this commit](https://github.com/opea-project/GenAIExamples/commit/4c01e1464273ae49909ab1eca337176588f8a027)

- ChatQnA/docker_compose/intel/hpu/gaudi/compose_vllm.yaml

Please verify if the helm charts and manifests need to be changed accordingly.

> This issue was created automatically by CI.

### PR DESCRIPTION
**Pull request by lianhao**
## Description

- Remove --eager-enforce on hpu to improve performance
- Refactor to the upstream docker entrypoint changes

## Issues

Fixes #631.

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Dependencies

List the newly introduced 3rd party dependency if exists.

## Tests

Describe the tests that you ran to verify your changes.

### CODE REVIEW

**Comment by eero-t** [comment]
Investigating the CI failure for "agent, gaudi, ci-gaudi-values, common" test, I see 2 bugs:
* agent `values.yaml` specifies (huge) `meta-llama/Meta-Llama-3.1-70B-Instruct` model for **CPU** version of TGI
  * https://github.com/opea-project/GenAIInfra/blob/main/helm-charts/common/agent/values.yaml#L10
  * Something that heavy should be used only for sharded accelerator configs, not for CPU!
* CI test does not provide HF token to access that for the sharded Gaudi TGI pods:
  * `[pod/agent20241211092531-tgi-6f6b65dc97-cjhjh/model-downloader] Access to model meta-llama/Llama-3.1-70B-Instruct is restricted. You must have access to it and be authenticated to access it. Please log in.`

**Comment by eero-t** [comment]
My vLLM PR includes same agent and (relevant) vLLM component changes as yours, but strangely that same CI agent test succeeded for it: https://github.com/opea-project/GenAIInfra/actions/runs/12262626198/job/34212355870?pr=610 ?

Any ideas why/how?

**Review by eero-t — COMMENTED** [review]
`--tensor-parallel-size` option can be dropped, as `1` value is the default:
https://docs.vllm.ai/en/latest/usage/engine_args.html

**Comment by lianhao** [comment]
This specific failure is caused by 2 different bugs: #639, #641

**Comment by lianhao** [comment]
we need to wait for PR #642 to land-in first

**Comment by lianhao** [comment]
Let's use #610 instead.

**Pull request closed without merging**
