### PR TITLE
Update comp manifest generation 

### PR DESCRIPTION
**Pull request by lianhao**
## Description

Change how component level manifests are generated for GMC

- Move all generated component level manifests into a common flat directory
- Disable k8s probes for GMC manifest
- Add tei-gaudi support
- Add generated component manifest files

## Issues

n/a

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds new functionality)

## Dependencies

n/a

## Tests

n/a

### CODE REVIEW

**Comment by lianhao** [comment]
The generated manifest examples are shown as https://github.com/lianhao/GenAIInfra/tree/manifest_show/manifests/common

**Comment by yongfengdu** [comment]
The manifests/README should also be updated.
Others looks good

**Comment by lianhao** [comment]
> The manifests/README should also be updated. Others looks good

@yongfengdu manifests/README is updated

**Review by yongfengdu — APPROVED** [review]

**Comment by irisdingbj** [comment]
Thanks @lianhao ,  Is it possible to remove the configmaps from manifests?  GMC will not use them(both the global one and the ones under each of the microservices).

**Review by irisdingbj — APPROVED** [review]

**Review by yongfengdu — APPROVED** [review]

**Pull request merged**
